language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"

branches:
  except:
    - deploy

install:
  - cp course/settings.py.example course/settings.py
  - cp user/mailsettings.py.example user/mailsettings.py
  - pip install -r requirements.txt

script: 
  - python3 manage.py migrate
  - python3 manage.py test


